switches:
  - name: s1
    dpid: "1"
  - name: s2
    dpid: "2"
  - name: s3
    dpid: "3"
  - name: s4
    dpid: "4"
  - name: s5
    dpid: "5"
links:
  - {src: s1, dst: s2, src_port: 2, dst_port: 1, weight: 1}
  - {src: s2, dst: s3, src_port: 3, dst_port: 2, weight: 1}
  - {src: s3, dst: s4, src_port: 4, dst_port: 3, weight: 1}
  - {src: s4, dst: s1, src_port: 1, dst_port: 4, weight: 5}
  - {src: s5, dst: s1, src_port: 1, dst_port: 5, weight: 5}
  - {src: s5, dst: s2, src_port: 2, dst_port: 5, weight: 5}
  - {src: s5, dst: s3, src_port: 3, dst_port: 5, weight: 5}
  - {src: s5, dst: s4, src_port: 4, dst_port: 5, weight: 5}
controller:
  name: c1
  ip: 127.0.0.1
  port: 6633

hosts:
  - name: h1
    switch: s2
    switch_port: 10
    mac: 00:00:00:00:00:01
    network: green
  - name: h2
    switch: s5
    switch_port: 10
    mac: 00:00:00:00:00:02
    network: blue
  - name: h3
    switch: s3
    switch_port: 10
    mac: 00:00:00:00:00:03
    network: green
    