                                         
                                       
    # vid 10                vid  20      
    #      │                      │      
    #      │                      │      
    #      │                      │      
    #      │                      │      
    #      │1                     │2     
    #   ┌──┴───┐               ┌──┴───┐  
    #   │      │               │      │  
    #   │  r1  ┼───────────────┤  r2  │  
    #   │      │ 2           1 │      │  
    #   └──┬───┘               └──┬───┘  
    #      │ 3                    │ 3    
    #      │                      │      
    #      │                      │      
    #      │ 1                    │      
    #   ┌──┴───┐                  │      
    #   │      │                  │      
    #   │  r3  ┼──────────────────┘      
    #   │      │ 2                       
    #   └──┬───┘                         
    #     3│                             
    #      │                             
    #      │                             
    #      │                             
    # vid 30                             
                                       

                                         
switches:
  - name: r1
    dpid: "1"
  - name: r2
    dpid: "2"
  - name: r3
    dpid: "3"
links:
  - src: r1
    dst: r2
    src_port: 2
    dst_port: 1
  - src: r2
    dst: r3
    src_port: 3 
    dst_port: 2
  - src: r1
    dst: r3
    src_port: 3 
    dst_port: 1

controller:
  name: c1
  ip: 192.168.0.100
  port: 6633
