switches:
  - name: r1
    dpid: "1"
  - name: r2
    dpid: "2"
  - name: r3
    dpid: "3"
  - name: r4
    dpid: "4"
links:
  - src: r1
    dst: r2
    src_port: 4 
    dst_port: 4
    delay: 1
  - src: r1
    dst: r4
    src_port: 3 
    dst_port: 3
    delay: 2
  - src: r2
    dst: r3
    src_port: 3 
    dst_port: 3
    delay: 3
  - src: r3
    dst: r4
    src_port: 4 
    dst_port: 4
    delay: 4

controller:
  name: c1
  ip: 192.168.0.100
  port: 6633

hosts:
  - name: h1
    switch: s2
    switch_port: 10
    mac: 00:00:00:00:00:01
    network: green
  - name: h2
    switch: s5
    switch_port: 10
    mac: 00:00:00:00:00:02
    network: blue
  - name: h3
    switch: s3
    switch_port: 10
    mac: 00:00:00:00:00:03
    network: green
    